version: '3.8'

services:
  node:
    build: ./node
    ports:
      - "4000:4000"
    volumes:
      - ./hls:/tmp/hls
    depends_on:
      - nginx

  nginx:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"   # RTMP ingest
      - "8080:80"     # HLS playback
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/tmp/hls